#+TITLE Emacs configuration How emacs completes
#+PROPERTY:header-args :cache yes :tangle yes :comments link

* Text
This is completion for text in buffer
** Current program
This looks at the current code and prompts for variables etc
I need something and company seems to be the current one
Add some from jweigley
 #+begin_src emacs-lisp
 (use-package company
   :ensure t
   :diminish
   :commands (company-mode company-indent-or-complete-common)

   :hook (after-init . global-company-mode)
   :config
   (define-key company-mode-map [tab]
     '(menu-item "maybe-company-expand" nil
                 :filter (lambda (&optional _)
                           (when (check-expansion)
                             #'company-complete-common))))
   )
#+end_src

** Language dependant
This depends on the major mode and helps in code structure
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :demand t                             ; need to force the load
  :after company
  :mode ("/\\.emacs\\.d/data/snippets/" . snippet-mode)

  :config
  (setq yas-snippet-dirs (list (mwb-user-emacs-file "data/snippets")))
  (yas-reload-all)
  (yas-global-mode 1)

  (defun company-mode/backend-with-yas (backend)
    (if (and (listp backend) (member 'company-yasnippet backend))
        backend
      (append (if (consp backend) backend (list backend))
              '(:with company-yasnippet))))
  (setq company-backends
        (mapcar #'company-mode/backend-with-yas company-backends))

  (use-package yasnippet-snippets
    :config (yasnippet-snippets-initialize)
    (message "loaded yasnippets collection")
    :ensure t)

  :hydra (hydra-yasnippet (:color blue :hint nil)
                          "
                ^YASnippets^
  --------------------------------------------
    Modes:    Load/Visit:    Actions:

   _g_lobal  _d_irectory    _i_nsert
   _m_inor   _f_ile         _t_ryout
   _e_xtra   _l_ist         _n_ew
           _a_ll
  "
                          ("d" yas-load-directory)
                          ("e" yas-activate-extra-mode)
                          ("i" yas-insert-snippet)
                          ("f" yas-visit-snippet-file :color blue)
                          ("n" yas-new-snippet)
                          ("t" yas-tryout-snippet)
                          ("l" yas-describe-tables)
                          ("g" yas/global-mode)
                          ("m" yas/minor-mode)
                          ("a" yas-reload-all))
  )
#+end_src

*** yasnippets collection
There is a package including a lot of snippets.
However there are so many elisp ones that it might be too confusing.
#+begin_src emacs-lisp

#+end_src

* Emacs
This is completion for emacs commands. Choice is ido, ivy helm.
I'll try ivy.
Note headers have tangle command in to suppress one or other
** Find M-x commands
  This is [[https://www.emacswiki.org/emacs/Smex][smex]] buy ivy replaces it actually it uses it - Something changed :(
  #+begin_quote
  Smex is a M-x enhancement for Emacs. Built on top of IDO, it provides a convenient interface to your recently and most frequently used commands. And to all the other commands, too.
  #+end_quote
  #+begin_src emacs-lisp
	(use-package smex
	  :ensure t
	  :config
	  (smex-initialize))
  #+end_src

** Ivy
#+begin_src emacs-lisp
(mwb-init-load "init/ivy")
#+end_src
