#+TITLE Emacs configuration - ibuffer
#+PROPERTY:header-args :cache yes :tangle yes :comments link
#+STARTUP: content
* Buffers
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:FADBA799-7985-455A-8BA0-5E6A6CC2C3DB
:END:

Ibuffer seems to be the one.
I would note that this is where use-package and other code reasons to keep together conflict with literate programming. Current use literate-programming but I suspect noweb is the way here once I have a working setup. use-package benefit includes a total fail if issue.
Current attempt is a halfway. Instead of noweb I call a new org file. This keeps all the code in org files as valid lisp. At some stage for e.g. hydra it might make sense for noweb as fragments are not valid lisp. An alternative is put other code in separate use-package bits with :defer t as per nasy.moe

There is some comment on internet that other things in ibuffer are a mess. I would say that the list of grouping is another.

This setup from [[https://emacs.nasy.moe/#org2ffc7b4][nasy.moe]] and others for the default and [[https://www.reddit.com/r/emacs/comments/64kr02/emacs_workflow_some_guidance_please/][reddit]] for the grouping

However much of the same code appears in many places so I don't know the real source

** Main use
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:1EDC2A71-58BD-4635-B02F-727C8677DC78
:END:
   The overall load.
   #+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_8FD96F98-B122-4E26-BC6D-62735E12E33F
   #+begin_src emacs-lisp
   (use-package ibuffer
	 :bind (("C-x C-b" . ibuffer)
			:map ibuffer-mode-map
			("." . hydra-mwb-ibuffer-main/body))
	 :init
	 (setq ibuffer-show-empty-filter-groups nil
		   ibuffer-default-sorting-mode 'filename/process)
	 :config
	 (mwb-init-load "init/ibuffer-config")
	 :hook (ibuffer . hydra-mwb-ibuffer-main/body))
   #+end_src

** Display functions
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:D26DEC0A-8956-4075-97A3-981E315788BB
:END:
#+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_30D55E18-A0EB-4BEC-A9AE-DC22DE1E317A
#+begin_src emacs-lisp
;; Use human readable Size column instead of original one
(define-ibuffer-column size-h
  (:name "Size" :inline nil)
  (let ((bs (buffer-size)))
	(cond ((> bs 1e6) (format "%7.1fMB" (/ bs 1e6)))
		  ((> bs 1e3) (format "%7.1fkB" (/ bs 1e3)))
		  (t          (format "%7d  " bs)))))

(setq ibuffer-formats
	  '((mark modified read-only vc-status-mini " "
			  (name 30 30 :left :elide)
			  " "
			  (size-h 9 -1 :right)
			  " "
			  (mode 10 10 :left :elide)
			  " "
			  (vc-status 10 10 :left)
			  " "
			  vc-relative-file)))
  #+end_src

** Groups
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:1256BA3D-288D-4B3D-B06D-1474969EF405
:END:
This is from  [[https://www.reddit.com/r/emacs/comments/64kr02/emacs_workflow_some_guidance_please/][reddit]]

*** Collapse buffer groups
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:05D42CAD-2C1C-4ABA-97A9-032C0C4F23DB
:END:
**** Choose the groups
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:29EEF179-59EF-4590-A610-25E7DF12014D
:END:
 #+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_77968D6B-1BBA-4161-B6E1-B81A674421AD
 #+begin_src emacs-lisp
(defvar gk-ibuffer-collapsed-groups
  (list
   "Special buffers"
   "Dired"
   "Emacs"
   "Aquamacs"
   "Emacs Documentation"
   "Help"
   "GNUs"
   "Magit"
   "Custom"
   "Helm"
   ;; "Special buffers"
   "EWW Reading"
   "VC"))
#+end_src
**** Do the collapsing
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:E192D834-8E4A-43CF-9F53-EA58B15D65DA
:END:
#+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_6423311D-14C1-4B74-8260-3839A650AB57
#+begin_src emacs-lisp
(define-advice ibuffer (:after (&rest args) gk-hidden-groups)
  "Hide groups in ‘gk-ibuffer-collapsed-groups’."
  (ignore args)
  (save-excursion
	(dolist (group gk-ibuffer-collapsed-groups)
	  (ignore-errors
		(ibuffer-jump-to-filter-group group)
		(ibuffer-toggle-filter-group)))))
#+end_src
**** Add the hook for the grouping
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:AA7E5412-2496-4BAC-AE50-D65C6DA0B6F9
:END:
#+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_A7D37C41-4530-4DD6-871B-B2B828F66B19
#+begin_src emacs-lisp
(cl-defun gk-ibuffer-hook ()
   (unless (eq ibuffer-sorting-mode 'alphabetic)
	 (ibuffer-do-sort-by-filename/process))
   (ibuffer-update nil t))

(add-hook 'ibuffer-hook 'gk-ibuffer-hook)
	#+end_src

** Put cursor on most recent buffer
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:1E688E4D-5D72-4CA0-9E65-A71F8DA4FDDE
:END:
   Switching to ibuffer puts the cursor on the most recent buffer and where advices go with use-package to be found out.

   #+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_07D7442D-D957-4B3A-9BB2-41582476445B
   #+begin_src emacs-lisp
   (defadvice ibuffer (around ibuffer-point-to-most-recent) ()
	 "Open ibuffer with cursor pointed to most recent buffer name"
	 (let ((recent-buffer-name (buffer-name)))
	   ad-do-it
	   (ibuffer-jump-to-buffer recent-buffer-name)))

   (ad-activate 'ibuffer)
   #+end_src
** Hydra
:PROPERTIES:
:ID:       org_mark_2020-01-24T17-28-10+00-00_mini12:7CD44DD7-1332-4C1C-8819-136859BF8AA8
:END:
   From [[https://github.com/abo-abo/hydra/wiki/Ibuffer][Hydra Wiki]]
   #+NAME: org_mark_2020-01-24T17-28-10+00-00_mini12_A6D8D69A-A7A1-431C-BC16-A34732A92A60
   #+begin_src emacs-lisp
(defhydra hydra-mwb-ibuffer-main (:color red :hint nil)
  "
   ^Mark^         ^Actions^         ^View^          ^Select^              ^Navigation^
   _m_: mark      _D_: delete       _g_: refresh    _q_: quit             _k_:   ↑    _h_
   _u_: unmark    _s_: save marked  _S_: sort       _TAB_: toggle         _RET_: visit
   _*_: specific  _a_: all actions  _/_: filter     _o_: other window     _j_:   ↓    _l_
   _t_: toggle    _._: toggle hydra _H_: help       C-o other win no-select
   "
  ("m" ibuffer-mark-forward)
  ("u" ibuffer-unmark-forward)
  ("*" hydra-ibuffer-mark/body :color blue)
  ("t" ibuffer-toggle-marks)

  ("D" ibuffer-do-delete)
  ("s" ibuffer-do-save)
  ("a" hydra-ibuffer-action/body :color blue)

  ("g" ibuffer-update)
  ("S" hydra-ibuffer-sort/body :color blue)
  ("/" hydra-ibuffer-filter/body :color blue)
  ("H" describe-mode :color blue)

  ("h" ibuffer-backward-filter-group)
  ("k" ibuffer-backward-line)
  ("l" ibuffer-forward-filter-group)
  ("j" ibuffer-forward-line)
  ("RET" ibuffer-visit-buffer :color blue)

  ("TAB" ibuffer-toggle-filter-group)

  ("o" ibuffer-visit-buffer-other-window :color blue)
  ("q" (lambda () (interactive) (quit-window 4)) :color blue)
  ("." nil :color blue))

(defhydra hydra-ibuffer-mark (:color teal :columns 5
                                     :after-exit (hydra-ibuffer-main/body))
  "Mark"
  ("*" ibuffer-unmark-all "unmark all")
  ("M" ibuffer-mark-by-mode "mode")
  ("m" ibuffer-mark-modified-buffers "modified")
  ("u" ibuffer-mark-unsaved-buffers "unsaved")
  ("s" ibuffer-mark-special-buffers "special")
  ("r" ibuffer-mark-read-only-buffers "read-only")
  ("/" ibuffer-mark-dired-buffers "dired")
  ("e" ibuffer-mark-dissociated-buffers "dissociated")
  ("h" ibuffer-mark-help-buffers "help")
  ("z" ibuffer-mark-compressed-file-buffers "compressed")
  ("b" hydra-ibuffer-main/body "back" :color blue))

(defhydra hydra-ibuffer-action (:color teal :columns 4
                                       :after-exit
                                       (if (eq major-mode 'ibuffer-mode)
                                           (hydra-ibuffer-main/body)))
  "Action"
  ("A" ibuffer-do-view "view")
  ("E" ibuffer-do-eval "eval")
  ("F" ibuffer-do-shell-command-file "shell-command-file")
  ("I" ibuffer-do-query-replace-regexp "query-replace-regexp")
  ("H" ibuffer-do-view-other-frame "view-other-frame")
  ("N" ibuffer-do-shell-command-pipe-replace "shell-cmd-pipe-replace")
  ("M" ibuffer-do-toggle-modified "toggle-modified")
  ("O" ibuffer-do-occur "occur")
  ("P" ibuffer-do-print "print")
  ("Q" ibuffer-do-query-replace "query-replace")
  ("R" ibuffer-do-rename-uniquely "rename-uniquely")
  ("T" ibuffer-do-toggle-read-only "toggle-read-only")
  ("U" ibuffer-do-replace-regexp "replace-regexp")
  ("V" ibuffer-do-revert "revert")
  ("W" ibuffer-do-view-and-eval "view-and-eval")
  ("X" ibuffer-do-shell-command-pipe "shell-command-pipe")
  ("b" nil "back"))

(defhydra hydra-ibuffer-sort (:color amaranth :columns 3)
  "Sort"
  ("i" ibuffer-invert-sorting "invert")
  ("a" ibuffer-do-sort-by-alphabetic "alphabetic")
  ("v" ibuffer-do-sort-by-recency "recently used")
  ("s" ibuffer-do-sort-by-size "size")
  ("f" ibuffer-do-sort-by-filename/process "filename")
  ("m" ibuffer-do-sort-by-major-mode "mode")
  ("b" hydra-ibuffer-main/body "back" :color blue))

(defhydra hydra-ibuffer-filter (:color amaranth :columns 4)
  "Filter"
  ("m" ibuffer-filter-by-used-mode "mode")
  ("M" ibuffer-filter-by-derived-mode "derived mode")
  ("n" ibuffer-filter-by-name "name")
  ("c" ibuffer-filter-by-content "content")
  ("e" ibuffer-filter-by-predicate "predicate")
  ("f" ibuffer-filter-by-filename "filename")
  (">" ibuffer-filter-by-size-gt "size")
  ("<" ibuffer-filter-by-size-lt "size")
  ("/" ibuffer-filter-disable "disable")
  ("b" hydra-ibuffer-main/body "back" :color blue))
   #+end_src
