#+TITLE Emacs configuration
#+PROPERTY:header-args :cache yes :tangle yes :comments link
#+STARTUP: content
* Overview

** Introduction
 OK I caught the bug to create an org mode file to document my init files.

 The reason is not for the pretty files that you see on the web or github but that I was writing a few comments and realised that org mode looks nicer for those (no comment marker ; on lines) and you can deal in text mode for documentation.

I would note that my programming style is to have lots of small functions. With org-mode I can execute code from a block and not from a tangle. Unfortunately for init files use-package wants you to pout all code into one lisp form so making comments away from code.

** Use of org mode

*** Tangling
Currently this is all being manually tangled and the generated
config.el is being checked in as well.

Ideally init.el should check config.org and all its sub org and if
needed generate a new config.el, then loads the config.el. Also try to
do without org mode as you won't have the up to date ine without
running the init. The best would be similar to
[[http://nullman.net/emacs/][nullman's init files]] where init is in
the same config file as the rest but generated by itself. I would have
started with his file but the org mode view is not available so I
can't create the correct header yet.
Re tangling I am happy to end with just org files and generate elisp
on the fly as I use GUIs and start emacs and leave it running - even
if I use docker that would be via tramp so still the main emacs.

*** Problems

**** TODO Spaces
 Current babel code encodes files with spaces by http encoding so result is not the sanme as the start. I think that this is not required in tangle but that is a code change. Safest fix is to move init files but need to deal with customisation

**** TODO Links
I tried to include all the org text in the source code but that adds extra links which seem to defeat detangle - but could be space related
*** Include
I want separate files - so when fiddling a mode then I can see it git
history easily what changed.
Methods seem to be
1. use org-mode's include
2.  else as [[https://github.com/eschulte/emacs24-starter-kit][Emacs starter kit]]. Which has a special elisp load of then
   org file. But this does not save .el to disk so issue with debugging
3. Just require the el file - you tangle the org file first. - but
   need to make them all save
There are also loaders that optionally load - but as I just have one
machine just load all.
With experience messing stuff up.
You need the .el to edit if crashed.

**** TODO Hack
Eventual is probably based off nullman.net
Start by tangle on save if in init dir [[https://emacs.stackexchange.com/a/20733/9874][SO answer]] and also do a
starterkit loader that check date of el and org and regenerates if
needed. Eventually the el file is not needed but let's convert fully
first (unless you need fast starts)

*** Aquamacs
 This file runs under Aquamacs, I use Aquamacs because it was the easiest distribution to set up in 2002. Nowadays with package loaders and starter kits this is not so needed.
 Aquamacs does have one advantage it uses Apple's spellchecker and that will not be rolled into GNU.
 Aquamacs though is old Aquamacs 3.4 GNU Emacs 25.3.50.1 Emacs is now on 26 and has been for over a year but if we just need new packages then version is OK.

**** user-emacs-directory
 This is the directory emacs reads and writers support files from. This is a mess as some are yours under version control and others are created on the fly. The ones on the fly can have the same name as packages and so stop loading (e.g. Tramp and Calc). There are several ways round this e.g. [[https://github.com/emacscollective/no-littering][No Littering]] Aquamacs does this by moving user-emacs-directory and putting the start dir on the load-path but also every possible directory so can't find it easily and hard codes paths and no use a directory so have to have our own const.

  Aquamacs does doup a lot into its directory and maes use-emacs-directory always this even if the config files are elsewhere.

 Now text based things donm't like spaces (programmers are lazy) I want a structured text editor
 The issue here is when tangling the references to files are encoded to remove spaces so the directopry becomes ~/Library/Preferences/Aquamacs%20Emacs so riund tripping fails.

***** DONE Need to move all init files into a path that has no spaces
	  CLOSED: [2019-05-06 Mon 02:21]

***** DONE Look at xak lee's get filename codes
	  CLOSED: [2019-05-04 Sat 04:57]

*** Load order
Startup files aquamacs looks in are site-start.el then init.el and in a
directory order not including ~/.emacs.d/
Aquamacs loads Preferences.el I just make that load init.el so I could
use a more standard emacs note that would need to deal with
customizations as Aquamacs already has set that. Also see [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][Emacs manual
on init-files]]
From  aquamacs-get-custom-file-dotemacs-warning
;; %s
;; Warning: After loading this .emacs file, Aquamacs will also load
;; customizations from `custom-file' (customizations.el). Any settings there
;; will override those made here.
;; Consider moving your startup settings to the Preferences.el file, which
;; is loaded after `custom-file':

* Implement
Full init
*** Control init environment
:PROPERTIES:
  :header-args:    :tangle init.el :comments link
  :END:
All this is tangled into init.el which is also under git.
**** Startup
 These are speedup and safety changes but note that  Aquamacs has probably already taken most of the time.

 Elisps and init files have two ways of doing this. One is to put the whole init inside a let block but I want each src block to be runnable from the org file so not good. The other is to set and copy old values at the beginning then use an end hook to put them back. A long term alternative is to make the loader function do that work.
 The time is probably not that useful - build on Aquamacs instead and there is an emacs profiler. I did get the Aquamacs nightly and that is much slower and displaying menus is an issue. I have changed accessibility in System Preferences->Privacy so we will see. Probably wait until mMacs 27 is out and use a plain emacs and see about spell checking
 The file-name-handler-alist is probably needed as some of the hooks slow things heavily

 This is from [[ https://github.com/jwiegley/dot-emacs/blob/master/init.el#L1013][John Wiegley]]
 #+begin_src emacs-lisp
 (defconst emacs-start-time (current-time))

 (defvar file-name-handler-alist-old file-name-handler-alist)

 (setq package-enable-at-startup nil
	   file-name-handler-alist nil
	   message-log-max 16384
	   gc-cons-threshold 402653184
	   gc-cons-percentage 0.6
	   auto-window-vscroll nil)
 #+end_src
**** Code to do loading
  Need to get the correct directory

  Function to load the code for this part of the init.
  Currently it just loads the .el of that name so could just be (load "mwb-init-load"). I now tangle all org-mode buffers on save. Eventually it will get the data from mwb-init-load.org and tangle it and use that.

**** Helper functions
Thse are required elisp for initialisation

***** Set where the init file is
 In constant mwb-user-emacs-directory
	  #+begin_src emacs-lisp
 ;; Need the directory from here.
 (defun mwb-get-directory-of-current-file ()
   "Return the full directory path of the caller's file location."
   (file-name-directory (or load-file-name buffer-file-name))
   )
 (defconst mwb-user-emacs-directory (mwb-get-directory-of-current-file))
	  #+end_src

***** Where my init code is
  See [[http://ergoemacs.org/emacs/organize_your_dot_emacs.html][Xah Lee get directory name for file]] for possible work around for user-emacs-directory. Except in some cases I do want the directory so break it up
  #+begin_src emacs-lisp
(defun mwb-user-emacs-file (name)
	"Return an absolute per-user Emacs-specific file name around where the init file is.
  It is basically locate-user-emacs-file but I have followed Aquiamacs is setting that not where my init.el file is.
  Main reason to use is so that I can put init under version control and the rest go elsewhere."
	(expand-file-name name mwb-user-emacs-directory))
  #+end_src
***** The loader
 Actually load the init files, protect is aquamacs macro to carch errors also see [[https://emacs.stackexchange.com/a/671/9874][Stack Exchange answer]]
This fails for config.org so that needs to be in version control.
   #+begin_src emacs-lisp
   (defun mwb-init-load (file-root)
	 "Load the relevant code. Currently just the same as load it loads
		 <file-root>.el but eventually will load <file-root>.org"
	 (let* ((org-file
			 (concat (expand-file-name file-root mwb-user-emacs-directory) ".org"))
			(el-file
			 (concat (expand-file-name file-root mwb-user-emacs-directory) ".el")))

	   (when (file-newer-than-file-p org-file el-file)
		 (require 'org)
		 (message "This loaded an org mode but from the system - best to restart")
		 (message "tangle <%s> to <%s>" org-file el-file)
		 (org-babel-tangle-file org-file el-file))
	   (protect (load el-file))))
      #+end_src
**** The Load
	 #+begin_src emacs-lisp
	 (mwb-init-load "config")
	 #+end_src
*** Emacs environment
Setup minimum to run the configuration.
I suspect the order after this does not matter
**** Debug flag
	 #+begin_src emacs-lisp
(setq init-file-debug nil)
	 #+end_src
**** After initialisation
Although see starter kit where they run after init.
  #+begin_src emacs-lisp

  (add-hook 'after-init-hook
			`(lambda ()
			   (setq file-name-handler-alist file-name-handler-alist-old
					 gc-cons-threshold 800000
					 gc-cons-percentage 0.1)
			   (garbage-collect)
			   (message "Emacs init-time %s" (emacs-init-time))) t)
  #+end_src
**** Emacs Lisp
***** Debugging
  This slows things down so for debugging outside init.
 But for debugging init

  #+begin_src emacs-lisp

  (add-hook 'after-init-hook
				 (lambda () (setq debug-on-error t)))
 ; (setq debug-on-error t)
  #+end_src
***** Use source where newer
 This variable tells Emacs to prefer the .el file if it’s newer, even if there is a corresponding .elc file.
	  #+begin_src emacs-lisp
(setq load-prefer-newer t)
	  #+end_src
**** Customisation file
 Yes Aquamacs does this but in a directory with a space. SO put with code so can be under source code control and user-emacs-directory is not.
 Needs to have initsplit added so can seperate out customization files.
 #+begin_src emacs-lisp
 (setq custom-file ( mwb-user-emacs-file "custom/custom.el"))
 (load custom-file 'noerror)
 #+end_src
**** Packaging
***** SSL  network connection
 Basically we need gnutls to connect via SSL as certificates have changed
 From https://github.com/paolodedios/dot-files/blob/1a7b4500c8ce07d0d473dbf714a2303f4d440ef5/.emacs.d/init.el
 Configure GnuTLS

 GnuTLS requires additional configuration on Emacs 25+ on macOS to prevent it
 from crashing when loading package repositories.

 @see https://github.com/davidswelt/aquamacs-emacs/issues/133
 @see https://github.com/davidswelt/aquamacs-emacs/issues/149
 @see https://www.reddit.com/r/emacs/comments/8sykl1/emacs_tls_defaults_are_downright_dangerous/
 @see https://www.gnu.org/software/emacs/manual/html_node/emacs-gnutls/Help-For-Users.html

  @note starttls.el and tls.el have been moved to obsolete in the master branch
  (what will be Emacs 27).
	 #+begin_src emacs-lisp

	 (require 'tls)

	 (with-eval-after-load 'tls
	   ;; Add the gnutls CA certificate file
	   (push "/private/etc/ssl/cert.pem"                gnutls-trustfiles)
	   ;; Add the curl CA certificate file from Macports
	   (push "/opt/local/share/curl/curl-ca-bundle.crt" gnutls-trustfiles)
	   )

	 ;; Validate TLS certificates
	 (setq gnutls-verify-error           t)

	 ;; Increase prime bits on TLS keys
	 (setq gnutls-min-prime-bits      2048)

	 ;; Network Security Module settings
	 ;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Network-Security.html
	 (setq network-security-level  'medium)
	 (setq nsm-save-host-names           t)

	 ;; Set tls-checktrust to `'ask` instead of `t` to allow user to determine
	 ;; whether or not to trust a certificate.
	 (setq tls-checktrust             'ask)

	 ;; Update the tls-program invocation command line string
	 ;;
	 ;; Add `--priority` flag to  prevents the 3des certificate from being used.
	 ;; Add `:%%PROFILE_MEDIUM` to ban intermediate SHA1 certificates.
	 ;; Add `--ocsp` flag to require certificate revocation check
	 ;;
	 ;; Add `--insecure` flag as a temporary workaround for the expired certificate
	 ;; on marmalade.org from hanging Aquamacs.
	 (setq tls-program
		   '("gnutls-cli -p %p --dh-bits=2048 --ocsp --x509cafile=%t --insecure \
	 --priority='SECURE192:+SECURE128:-VERS-ALL:+VERS-TLS1.2:%%PROFILE_MEDIUM' %h"))
	 #+end_src
***** Package Manager
 Initialize packages immediately and not after init.el is read post startup
 Not that Aquuamacs set these repositories.
	   #+begin_src emacs-lisp
 (require 'package)
 (setq package-enable-at-startup nil)
 ;(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))'
 ;(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
 ;(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
 (package-initialize)
	   #+end_src
***** Macros to set up how modes are set up
****** use-package
 include use-package setup from <https://github.com/CachesToCaches/getting_started_with_use_package/blob/master/init-use-package.el>
 #+begin_src emacs-lisp
 (unless (package-installed-p 'use-package)
   (package-refresh-contents)
   (package-install 'use-package))

 ;; Enable use-package
 (eval-when-compile
   (require 'use-package)
   (if init-file-debug
	   (setq use-package-verbose t
			 use-package-expand-minimally nil
			 use-package-compute-statistics t
			 debug-on-error t)
	 (setq use-package-verbose nil
		   use-package-expand-minimally t)))
 #+end_src
****** Extras needed for loading
 These are used in the use-package macro
******* Diminish
 Mark if the mode being setup should not show in the mode/status line.
  #+begin_src emacs-lisp
  (use-package diminish   :ensure t   :demand t)
  #+end_src
******* Hydra
   Need key setting menus.
   #+begin_src emacs-lisp
   (use-package hydra :ensure t)
   (use-package use-package-hydra :ensure t)
   #+end_src
**** Setting variables with a check on type
Used when overriding a defcustom or defvar.
Note should check on defconst
#+begin_src emacs-lisp
(use-package validate
  :ensure t)
#+end_src

*** Emacs server
 This is a simple server start - to allow emacsclient from Terminal. There are more complex starters.
 #+begin_src emacs-lisp
(use-package server
  :ensure nil
  :hook (after-init . server-mode))
 #+end_src

*** Emacs settings
**** Apperance
 #+begin_src emacs-lisp
 (mwb-init-load  "mwb-init-appearance")
  #+end_src

**** Emacs behaviour
 General emacs stuff - not common-setup used to have this but separate file might not make sense
  #+begin_src emacs-lisp
  (mwb-init-load  "mwb-init-emacs-behaviour"); odds mainly variables
  (mwb-init-load  "mwb-init-ibuffer")

  #+end_src
*** Applications
**** Gnus
	 #+begin_src emacs-lisp
	 (mwb-init-load "mwb-init-gnus")
	 #+end_src
*** Major modes

***** System management
Interfacing with the operating system
  #+begin_src emacs-lisp
  (mwb-init-load "mwb-init-file-management")
  #+end_src

***** Text modes
****** Org Mode
	 #+begin_src emacs-lisp
	 (mwb-init-load "mwb-init-org-mode")
	 #+end_src

****** Epub reading
	   #+begin_src emacs-lisp
	   ;; Epub reader
	   (use-package nov
		 :ensure t
		 :mode ("\\.epub\\'" . nov-mode)
		 :preface
		 (defun my-nov-setup ()
		   (visual-line-mode 1)
		   (face-remap-add-relative 'variable-pitch :family "Times New Roman" :height 1.5)
		   :hook (nov-mode . my-nov-setup)))
	   #+end_src
***** Programming modes
Includes structured data
#+begin_src emacs-lisp
(mwb-init-load "mwb-init-prog-modes")
 #+end_src
*** Key binding
  No comments as just open the files.
  #+begin_src emacs-lisp
  (mwb-init-load "mwb-init-global-keys")
  #+end_src
