#+TITLE Emacs configuration
#+PROPERTY:header-args :results output :session :cache yes :tangle yes :comments org :exports both
#+STARTUP: content

* Overview

** Introduction
 OK I caught the bug to create an org mode file to document my init files.

 The reason is not for the pretty files that you see on the web or github but that I was writing a few comments and realised that org mode looks nicer for those (no comment marker ; on lines) and you can deal in text mode for documentation.

** Use of org mode

*** Tangling
Currently this is all being manually tangled and the generated
config.el is being checked in as well.

Ideally init.el should check config.org and all its sub org and if
needed generate a new config.el, then loads the config.el. Also try to
do without org mode as you won't have the up to date ine without
running the init. The best would be similar to
[[http://nullman.net/emacs/][nullman's init files]] where init is in
the same config file as the rest but generated by itself. I would have
started with his file but the org mode view is not available so I
can't create the correct header yet.
Re tangling I am happy to end with just org files and generate elisp
on the fly as I use GUIs and start emacs and leave it running - even
if I use docker that would be via tramp so still the main emacs.

*** Include
I want separate files - so when fiddling a mode then I can see it git
history easily what changed.
Methods seem to be
1. use org-mode's include
2.  else as [[https://github.com/eschulte/emacs24-starter-kit][Emacs starter kit]]. Which has a special elisp load of then
   org file. But this does not save .el to disk so issue with debugging
3. Just require the el file - you tangle the org file first. - but
   need to make them all save
There are also loaders that optionally load - but as I just have one
machine just load all.
With experience messing stuff up.
You need the .el to edit if crashed.

**** TODO Hack
Eventual is probably based off nullman.net
Start by tangle on save if in init dir [[https://emacs.stackexchange.com/a/20733/9874][SO answer]] and also do a
starterkit loader that check date of el and org and regenerates if
needed. Eventually the el file is not needed but let's convert fully
first (unless you need fast starts)

** Aquamacs
This file runs under Aquamacs, I use Aquamacs because it was the easiest distribution to set up in 2002. Nowadays with package loaders and starter kits this is not so needed.
Aquamacs does have one advantage it uses Apple's spellchecker and that will not be rolled into GNU.
Aquamacs though is old Aquamacs 3.4 GNU Emacs 25.3.50.1 Emacs is now on 26 and has been for over a year but if we just need new packages then version is OK.

*** user-emacs-directory
This is the directory emacs reads and writers support files from. This is a mess as some are yours under version control and others are created on the fly. The ones on the fly can have the same name as packages and so stop loading (e.g. Tramp and Calc). There are several ways round this e.g. [[https://github.com/emacscollective/no-littering][No Littering]] Aquamacs does this by moving user-emacs-directory and putting the start dir on the load-path but also every possible directory so can't find it easily and hard codes paths and no use a directory so have to have our own const.

* Control init
This sets up variables and environment to run the init.
*** Load order
Startup files aquamacs looks in are site-start.el then init.el and in a
directory order not including ~/.emacs.d/
Aquamacs loads Preferences.el I just make that load init.el so I could
use a more standard emacs note that would need to deal with
customizations as Aquamacs already has set that. Also see [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][Emacs manual
on init-files]]
*** Control init environment
These are speedup and safety changes but note that  Aquamacs has probably already taken most of the time.

Elisps and init files have two ways of doing this. One is to put the whole init inside a let block but I want each src block to be runnable from the org file so not good. The other is to set and copy old values at the beginning then use an end hook to put them back. A long term alternative is to make the loader function do that work.
The time is probably not that useful - build on Aquamacs instead and there is an emacs profiler. I did get the Aquamacs nightly and that is much slower and displaying menus is an issue. I have changed accessibility in System Preferences->Privacy so we will see. Probably wait until mMacs 27 is out and use a plain emacs and see about spell checking
The file-name-handler-alist is probably needed as some of the hooks slow things heavily

This is from [[ https://github.com/jwiegley/dot-emacs/blob/master/init.el#L1013][John Wiegley]]
#+begin_src emacs-lisp

(defconst emacs-start-time (current-time))

(defvar file-name-handler-alist-old file-name-handler-alist)

(setq package-enable-at-startup nil
	  file-name-handler-alist nil
      message-log-max 16384
      gc-cons-threshold 402653184
      gc-cons-percentage 0.6
      auto-window-vscroll nil)


(add-hook 'after-init-hook
          `(lambda ()
             (setq file-name-handler-alist file-name-handler-alist-old
                   gc-cons-threshold 800000
                   gc-cons-percentage 0.1)
             (garbage-collect)) t)

#+end_src
**** Emacs Lisp debugging
 This slows things down so for debugging outside init.
But for debugging init

 #+begin_src emacs-lisp

 (add-hook 'after-init-hook
				(lambda () (setq debug-on-error t)))
 (setq debug-on-error t)
 #+end_src

**** Code to do loading
  Need to get the correct directory

  Function to load the code for this part of the init.
  Currently it just loads the .el of that name so could just be (load "load-mwb-init"). I now tangle all org-mode buffers on save. Eventually it will get the data from load-mwb-init.org and tangle it and use that.

  See [[http://ergoemacs.org/emacs/organize_your_dot_emacs.html][Xah Lee get directory name for file]] for possible work around for user-emacs-directory
  #+begin_src emacs-lisp
  (defun load-mwb-init (file-root)
	"Load the relevant code. Currently just the same as load it loads
  <file-root>.el but eventually will load <file-root>.org"
	(load file-root))
  #+end_src

**** Packaging
Old elisp
  #+begin_src emacs-lisp

 (load "setup-packages") ; Package management
  #+end_src

**** Emacs server
 This is a simple server start - to allow emacsclient from Terminal. There are more complex starters.
 #+begin_src emacs-lisp

 (server-start)
 #+end_src

**** Emacs behaviour
General emacs stuff - not common-setup used to have this but separate file might not make sense
 #+begin_src emacs-lisp
 (load-mwb-init "mwb-init-file-management")
 #+end_src
* Remains
This is all the includes

** New ones
 #+begin_src emacs-lisp
 (load-mwb-init "mwb-init-org-mode")

 #+end_src

** remains
 #+begin_src emacs-lisp



 ;; common bits
 (load "common-setup") ; odds mainly variables
 (load "common-programming") ; modes for programming
 #+end_src

* New loading
** The new versions to be loaded
No comments as just open the files.
#+begin_src emacs-lisp
(load-mwb-init "mwb-init-global-keys")
#+end_src
