(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(calibredb
	 flycheck-swift
	 swift-helpful
	 swift-mode
	 fsharp-mode
	 markdown-mode
	 bison-mode
	 dockerfile-mode
	 with-editor
	 emr
	 selectrum-prescient
	 selectrum
	 embark-consult
	 embark
	 marginalia
	 discover-my-major
	 iedit
	 treemacs-magit
	 treemacs-icons-dired
	 auto-compile
	 consult
	 keyfreq
	 modus-themes
	 all-the-icons-completion
	 git-messenger
	 org-capture
	 treemacs-projectile
	 treemacs
	 mini-frame
	 rg
	 rainbow-mode
	 spaceline-all-the-icons
	 spaceline
	 minions
	 free-keys
	 company-quickhelp
	 python-mode
	 xterm-color
	 srefactor-lisp
	 transient-posframe
	 dired-subtree
	 company-math
	 git-timemachine
	 magit
	 async
	 paradox
	 gcmh
	 flyspell
	 persistent-scratch
	 amx
	 dtrt-indent
	 color-identifiers
	 color-identifiers-mode
	 srefactor
	 flycheck-yamllint
	 yaml-mode
	 toc-org
	 lisp-extra-font-lock
	 fira-code-mode
	 paren-face
	 flyspell-correct-popup
	 company-prescient
	 company-posframe
	 which-key-posframe
	 which-key-posframe-mode
	 hydra
	 s
	 dash
	 use-package
	 which-key
	 racket-mode
	 elmacro
	 lispy
	 rainbow-delimiters
	 flycheck
	 smartparens
	 highlight-indent-guides
	 nov
	 ibuffer-vc
	 projectile
	 deadgrep
	 prescient
	 yasnippet
	 company
	 helpful
	 smartparens-config
	 all-the-icons
	 major-mode-hydra
	 eval-in-repl
	 xr
	 yasnippet-snippets
	 outshine
	 expand-region
	 json-navigator
	 mwim
	 fish-mode
	 sml-mode
	 cmake-mode
	 cask-mode
	 eros
	 macrostep
	 org-indent
	 validate
	 hardhat
	 beacon
	 gitignore-mode
	 gitconfig-mode
	 use-package-hydra
	 backup-each-save
	 org-bullets
	 ws-butlerz
	 elisp-format
	 comment-dwim-2
	 json-mode
	 dired-toggle
	 aggressive-indent
	 gradle-mode
	 groovy-mode
	 ws-butler
	 diminish)))
