(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(all-the-icons-completion
	 git-messenger
	 org-capture
	 treemacs-projectile
	 treemacs
	 mini-frame
	 rg
	 all-the-icons-ivy-rich
	 rainbow-mode
	 spaceline-all-the-icons
	 spaceline
	 minions
	 moody
	 free-keys
	 company-quickhelp
	 python-mode
	 flycheck-swiftx
	 ob-swift
	 swift-helpful
	 swift-mode
	 swift-playground-mode
	 xterm-color
	 srefactor-lisp
	 transient-posframe
	 dired-subtree
	 company-math
	 git-timemachine
	 diff-hl
	 magit
	 async
	 paradox
	 gcmh
	 flyspell
	 color-theme-modern
	 persistent-scratch
	 all-the-icons-dired
	 amx
	 dtrt-indent
	 color-identifiers
	 color-identifiers-mode
	 srefactor
	 flycheck-yamllint
	 yaml-mode
	 toc-org
	 lisp-extra-font-lock
	 fira-code-mode
	 paren-face
	 flyspell-correct-popup
	 company-prescient
	 company-posframe
	 which-key-posframe
	 which-key-posframe-mode
	 mac-key-mode
	 hydra
	 s
	 dash
	 use-package
	 which-key
	 racket-mode
	 elmacro
	 lispy
	 rainbow-delimiters
	 flycheck
	 smartparens
	 highlight-indent-guides
	 nov
	 ibuffer-vc
	 projectile
	 deadgrep
	 ivy-prescient
	 prescient
	 yasnippet
	 company
	 helpful
	 org
	 smartparens-config
	 all-the-icons
	 major-mode-hydra
	 eval-in-repl
	 xr
	 yasnippet-snippets
	 outshine
	 expand-region
	 json-navigator
	 mwim
	 fish-mode
	 sml-mode
	 use-package-chords
	 cmake-mode
	 cask-mode
	 eros
	 macrostep
	 org-indent
	 validate
	 hardhat
	 beacon
	 gitignore-mode
	 gitconfig-mode
	 manual
	 use-package-hydra
	 backup-each-save
	 org-bullets
	 ws-butlerz
	 helm
	 elisp-format
	 comment-dwim-2
	 discover-my-major
	 json-mode
	 dired-toggle
	 aggressive-indent
	 gradle-mode
	 groovy-imports
	 groovy-mode
	 ws-butler
	 diminish
	 key-chord)))
